name: Auto-assign Issues & PRs to Org Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-and-sort:
    name: Add item to project and set column
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        id: add-item
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/SecQDevOps/projects/3
          github-token: ${{ secrets.PROJECT_AUTO_ADD_TOKEN }}

      - name: Move Issue to "inbox"
        if: github.event_name == 'issues'
        env:
          GH_TOKEN: ${{ secrets.PROJECT_AUTO_ADD_TOKEN }}
        run: |
          gh project item-edit --id "${{ steps.add-item.outputs.itemId }}" \
            --project-id "${{ steps.add-item.outputs.projectId }}" \
            --field "Status" \
            --single-select-option "inbox"

      - name: Move PR to "review"
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.PROJECT_AUTO_ADD_TOKEN }}
        run: |
          gh project item-edit --id "${{ steps.add-item.outputs.itemId }}" \
            --project-id "${{ steps.add-item.outputs.projectId }}" \
            --field "Status" \
            --single-select-option "review"
